---
- name: Update yum package cache (CentOS/RHEL)
  yum:
    update_cache: yes

- name: Install necessary packages for CentOS/RHEL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip
    - wget