---
- name: Update apt package cache (Debian/Ubuntu)
  apt:
    update_cache: yes

- name: Install necessary packages for Debian/Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip
    - wget
